window.STORY_LIBRARY = [
  { id: 'st1', theme: '자동차', title: '반짝반짝 차고의 밤', desc: '시현이가 자동차 친구들의 밤 준비를 도와요.', readingMinutes: 5, hasFullContent: true, contentKey: 'car_garage_night', characters: ['시현', '포키', '빨간 소방차', '작은 버스'] },
  { id: 'st2', theme: '자동차', title: '덤프트럭의 선물', desc: '무거운 돌 대신 마음을 나르는 트럭 이야기', readingMinutes: 5, hasFullContent: false, contentKey: 'car_dump_gift', characters: ['시현', '덤프트럭 두두'] },
  { id: 'st3', theme: '자동차', title: '경찰차 삐용이의 약속', desc: '길 잃은 장난감을 찾아 주는 따뜻한 순찰', readingMinutes: 5, hasFullContent: false, contentKey: 'car_police_promise', characters: ['시현', '삐용이'] },
  { id: 'st4', theme: '자동차', title: '소방차의 물방울 행진', desc: '칙칙폭폭 물방울들이 마을 꽃밭을 살려요.', readingMinutes: 5, hasFullContent: false, contentKey: 'car_fire_water', characters: ['시현', '소방차 대장'] },
  { id: 'st5', theme: '공룡', title: '티라노의 조용한 발걸음', desc: '쿵쿵 걷던 티라노가 살금살금 걷는 법을 배워요.', readingMinutes: 5, hasFullContent: true, contentKey: 'dino_soft_steps', characters: ['시현', '토토 티라노', '브라키오'] },
  { id: 'st6', theme: '공룡', title: '날아라 프테라노돈', desc: '하늘을 나는 공룡과 바람 리본을 찾아요.', readingMinutes: 5, hasFullContent: false, contentKey: 'dino_ptera_ribbon', characters: ['시현', '프테라'] },
  { id: 'st7', theme: '공룡', title: '트리케라톱스의 반짝 뿔', desc: '멋진 뿔에 별빛 스티커가 붙었어요.', readingMinutes: 5, hasFullContent: false, contentKey: 'dino_tricera_horn', characters: ['시현', '트리'] },
  { id: 'st8', theme: '공룡', title: '브라키오의 긴 목 우체통', desc: '높은 나뭇잎 편지를 배달하는 공룡 우체부', readingMinutes: 5, hasFullContent: false, contentKey: 'dino_brachio_mail', characters: ['시현', '브라키오'] },
  { id: 'st9', theme: '동물', title: '토끼와 거북이의 쉬는 시간', desc: '천천히 가도 괜찮다는 숲속 이야기', readingMinutes: 5, hasFullContent: false, contentKey: 'animal_rabbit_turtle_rest', characters: ['시현', '토끼', '거북이'] },
  { id: 'st10', theme: '동물', title: '사자왕의 생일 풍선', desc: '어흥 대신 하하 웃는 생일 파티', readingMinutes: 5, hasFullContent: false, contentKey: 'animal_lion_birthday', characters: ['시현', '사자왕'] },
  { id: 'st11', theme: '동물', title: '아기 곰의 당근 수프', desc: '보글보글 수프를 나누어 먹어요.', readingMinutes: 5, hasFullContent: false, contentKey: 'animal_bear_soup', characters: ['시현', '아기 곰'] },
  { id: 'st12', theme: '동물', title: '기린의 높은 인사', desc: '키 큰 기린이 낮게 고개 숙여 인사해요.', readingMinutes: 5, hasFullContent: false, contentKey: 'animal_giraffe_hello', characters: ['시현', '기린'] },
  { id: 'st13', theme: '우주', title: '달나라 로켓 정비소', desc: '슈웅 떠나기 전 로켓을 뚝딱 고쳐요.', readingMinutes: 5, hasFullContent: false, contentKey: 'space_moon_rocket', characters: ['시현', '달토끼'] },
  { id: 'st14', theme: '우주', title: '별똥별 주머니', desc: '반짝반짝 별 조각을 조심히 담아요.', readingMinutes: 5, hasFullContent: false, contentKey: 'space_star_pocket', characters: ['시현', '별 요정'] },
  { id: 'st15', theme: '우주', title: '화성 모래 케이크', desc: '빨간 모래로 만드는 폭신한 상상 케이크', readingMinutes: 5, hasFullContent: false, contentKey: 'space_mars_cake', characters: ['시현', '로봇 모모'] },
  { id: 'st16', theme: '우주', title: '우주선의 잠깐 낮잠', desc: '삐빅 우주선도 쉬어야 다시 날 수 있어요.', readingMinutes: 5, hasFullContent: false, contentKey: 'space_ship_nap', characters: ['시현', '우주선 반짝이'] },
  { id: 'st17', theme: '바다', title: '아기 고래 뚜루의 노래', desc: '출렁출렁 바다에서 노래를 찾아요.', readingMinutes: 5, hasFullContent: false, contentKey: 'sea_whale_song', characters: ['시현', '뚜루'] },
  { id: 'st18', theme: '바다', title: '꽃게의 집게발 박수', desc: '짝짝짝 박수로 친구들을 응원해요.', readingMinutes: 5, hasFullContent: false, contentKey: 'sea_crab_clap', characters: ['시현', '꽃게 까미'] },
  { id: 'st19', theme: '바다', title: '상어의 양치 시간', desc: '뾰족한 이를 반짝반짝 닦는 이야기', readingMinutes: 5, hasFullContent: false, contentKey: 'sea_shark_toothbrush', characters: ['시현', '상어 샤샤'] },
  { id: 'st20', theme: '바다', title: '거북이 등딱지 택배', desc: '등딱지 위에 작은 선물을 싣고 가요.', readingMinutes: 5, hasFullContent: false, contentKey: 'sea_turtle_delivery', characters: ['시현', '거북이 토리'] },
  { id: 'st21', theme: '전래', title: '흥부네 제비의 작은 지도', desc: '착한 마음을 따라가는 전래 느낌 모험', readingMinutes: 5, hasFullContent: false, contentKey: 'folk_swallow_map', characters: ['시현', '제비'] },
  { id: 'st22', theme: '전래', title: '호랑이와 달콤한 곶감', desc: '무섭지 않은 호랑이와 곶감 나눔', readingMinutes: 5, hasFullContent: false, contentKey: 'folk_tiger_persimmon', characters: ['시현', '호랑이'] },
  { id: 'st23', theme: '전래', title: '금도끼 은도끼 물방울', desc: '정직한 마음이 반짝이는 산속 이야기', readingMinutes: 5, hasFullContent: false, contentKey: 'folk_axes_drop', characters: ['시현', '산신령'] },
  { id: 'st24', theme: '이솝', title: '개미와 베짱이의 도시락', desc: '부지런함과 나눔을 함께 배우는 이야기', readingMinutes: 5, hasFullContent: false, contentKey: 'aesop_ant_lunch', characters: ['시현', '개미', '베짱이'] },
  { id: 'st25', theme: '이솝', title: '양치기 소년의 진짜 종소리', desc: '솔직하게 말하는 연습을 해요.', readingMinutes: 5, hasFullContent: false, contentKey: 'aesop_shepherd_bell', characters: ['시현', '양치기'] },
  { id: 'st26', theme: '이솝', title: '여우와 두루미의 새 그릇', desc: '서로 편한 방법을 생각해요.', readingMinutes: 5, hasFullContent: false, contentKey: 'aesop_fox_crane_bowl', characters: ['시현', '여우', '두루미'] },
  { id: 'st27', theme: '잠자리', title: '구름 양탄자의 자장가', desc: '폭신폭신 구름이 잠자리까지 데려다줘요.', readingMinutes: 5, hasFullContent: true, contentKey: 'bed_cloud_lullaby', characters: ['시현', '구름 양탄자', '달님'] },
  { id: 'st28', theme: '잠자리', title: '별 요정의 작은 등불', desc: '반짝 등불을 따라 마음이 조용해져요.', readingMinutes: 5, hasFullContent: false, contentKey: 'bed_star_lamp', characters: ['시현', '별 요정'] },
  { id: 'st29', theme: '잠자리', title: '달님의 뽀뽀 배달', desc: '창문가에 도착한 굿나잇 인사', readingMinutes: 5, hasFullContent: false, contentKey: 'bed_moon_kiss', characters: ['시현', '달님'] },
  { id: 'st30', theme: '잠자리', title: '꿈속 자동차의 느린 길', desc: '부릉부릉 천천히 꿈나라로 가요.', readingMinutes: 5, hasFullContent: false, contentKey: 'bed_dream_car', characters: ['시현', '꿈 자동차'] }
];

window.STORY_CONTENTS = {
  car_garage_night: {
    title: '반짝반짝 차고의 밤',
    theme: '자동차',
    paragraphs: [
      '해가 산 뒤로 쏙 들어가자, 우리집 작은 차고에 노란 불빛이 톡 켜졌어요. 시현이는 잠옷 위에 작은 정비사 조끼를 걸치고 차고 문을 살짝 열었지요.',
      '문이 끼이익 열리자 자동차 친구들이 조용히 인사했어요. 포크레인 포키는 팔을 살랑살랑 흔들고, 빨간 소방차는 삐뽀 대신 뿌웅 하고 작은 숨을 쉬었어요.',
      '오늘은 차고 친구들이 모두 잠자기 전 점검을 받는 날이었어요. 시현이는 손전등을 들고 "하나씩 천천히 보자" 하고 말했어요.',
      '먼저 포키의 바퀴를 보았어요. 바퀴 사이에 작은 나뭇잎이 끼어 있어서 달릴 때 사각사각 소리가 났지요.',
      '시현이가 집게로 나뭇잎을 쏙 빼 주자 포키가 기분 좋게 팔을 올렸어요. "고마워, 이제 굴러갈 때 데굴데굴 부드러워졌어."',
      '다음은 빨간 소방차였어요. 소방차의 물 호스가 돌돌돌 너무 단단하게 감겨 있었어요.',
      '시현이는 호스를 조금 풀고 다시 폭신하게 감아 주었어요. 호스는 꼬불꼬불 웃는 모양이 되었고, 소방차는 반짝 불빛을 한 번 깜빡였어요.',
      '작은 버스는 의자가 삐뚤빼뚤해서 손님 장난감들이 자꾸 옆으로 기울어진다고 했어요. 시현이는 의자를 톡톡 밀어 줄을 맞추었어요.',
      '그러자 장난감 곰, 장난감 로봇, 장난감 토끼가 모두 똑바로 앉았어요. 작은 버스 안에서는 "딩동, 편안합니다" 하는 귀여운 소리가 났어요.',
      '차고 구석에서는 택배차가 조용히 기다리고 있었어요. 택배차 안에는 내일 아침 가족에게 줄 작은 그림 편지가 들어 있었지요.',
      '시현이는 편지가 구겨지지 않도록 납작한 상자에 살포시 넣었어요. 상자 위에는 별 스티커도 꾹 붙여 주었답니다.',
      '모든 자동차가 점검을 마치자 차고 천장에 달린 작은 별 전구들이 하나씩 반짝였어요. 반짝, 반짝, 마치 자동차들이 고맙다고 박수치는 것 같았어요.',
      '포키가 낮은 목소리로 말했어요. "시현아, 오늘 우리를 천천히 살펴봐 줘서 마음이 따뜻해."',
      '시현이는 자동차 친구들을 한 대씩 쓰다듬었어요. 차가운 차체도 손끝에서는 포근하게 느껴졌어요.',
      '이제 차고도 잠잘 시간이 되었어요. 시현이는 불빛을 조금 낮추고 "내일 또 재미있게 달리자" 하고 속삭였어요.',
      '자동차 친구들은 부릉부릉 아주 작은 자장가를 불렀어요. 시현이는 그 소리를 들으며 방으로 돌아와 이불 속에 쏙 들어갔답니다.',
      '창밖 차고의 별 전구가 마지막으로 한 번 반짝였어요. 시현이는 "잘 자, 내 자동차 친구들" 하고 말하고 따뜻한 꿈나라로 천천히 떠났어요.'
    ]
  },
  dino_soft_steps: {
    title: '티라노의 조용한 발걸음',
    theme: '공룡',
    paragraphs: [
      '초록 숲 공룡 마을에는 토토라는 티라노가 살았어요. 토토는 마음은 아주 다정했지만 걸을 때마다 쿵쿵쿵 큰 소리가 났어요.',
      '아침이 되면 나뭇잎이 팔랑팔랑 흔들리고, 작은 도토리들이 데구루루 굴러갔어요. 토토는 깜짝 놀란 친구들을 보며 미안한 마음이 들었지요.',
      '그때 시현이가 공룡 모자를 쓰고 숲길로 찾아왔어요. 시현이는 토토에게 손을 흔들며 "우리 같이 조용히 걷는 연습을 해 볼까?" 하고 말했어요.',
      '토토는 커다란 발을 내려다보았어요. "내 발이 너무 커서 어려울 것 같아."',
      '시현이는 고개를 저었어요. "큰 발도 천천히 내려놓으면 폭신폭신 걸을 수 있어."',
      '둘은 먼저 이끼 길 위에서 연습했어요. 시현이가 한 발을 살짝 놓자 사뿐, 토토가 따라 하자 푹신 하는 소리가 났어요.',
      '토토는 웃으며 다시 해 보았어요. 쿵 대신 퐁, 쿵 대신 퐁, 숲길에 작은 북소리 같은 발걸음이 생겼어요.',
      '브라키오가 긴 목을 숙이고 구경하러 왔어요. "토토야, 네 발소리가 오늘은 구름 같구나."',
      '토토는 기분이 좋아 꼬리를 살랑 흔들었어요. 그런데 꼬리가 덤불을 휙 건드려 나뭇잎이 우수수 떨어졌어요.',
      '시현이는 웃으며 말했어요. "발만 조용히 하는 게 아니라 꼬리도 천천히 인사하면 돼."',
      '토토는 꼬리를 오른쪽으로 살랑, 왼쪽으로 살랑 움직였어요. 나뭇잎은 놀라지 않고 바람처럼 팔랑팔랑 춤추었어요.',
      '조금 뒤 작은 공룡들이 낮잠을 자는 언덕에 도착했어요. 토토는 아주 천천히 숨을 들이쉬고 한 발씩 사뿐사뿐 걸었어요.',
      '작은 공룡들은 깨지 않았어요. 오히려 토토의 부드러운 발걸음이 자장가처럼 들려 쌔근쌔근 더 편하게 잠들었어요.',
      '토토는 눈이 동그래졌어요. "나도 친구들을 편안하게 해 줄 수 있구나."',
      '시현이는 토토의 커다란 발등을 톡톡 두드렸어요. "응, 힘센 발은 조심히 쓰면 아주 따뜻한 발이 돼."',
      '저녁이 되자 공룡 마을 친구들이 토토에게 폭신한 잎사귀 길을 선물했어요. 토토는 그 길 위를 퐁퐁 걸으며 모두에게 고맙다고 했지요.',
      '그날 밤 토토는 처음으로 자기 발소리를 좋아하게 되었어요. 시현이도 공룡 숲의 조용한 별빛 아래에서 마음이 포근해졌답니다.'
    ]
  },
  bed_cloud_lullaby: {
    title: '구름 양탄자의 자장가',
    theme: '잠자리',
    paragraphs: [
      '밤이 되자 시현이 방 창문 밖에 하얀 구름 하나가 둥실둥실 떠왔어요. 구름은 네모난 양탄자처럼 납작하고 폭신해 보였어요.',
      '구름 양탄자는 창문을 톡톡 두드렸어요. "시현아, 오늘 하루도 많이 놀았지? 잠자리 산책을 같이 갈래?"',
      '시현이는 작은 담요를 어깨에 두르고 구름 위에 살포시 앉았어요. 구름은 솜사탕처럼 폭신해서 엉덩이가 푹 들어갔답니다.',
      '구름 양탄자는 아주 천천히 하늘로 올라갔어요. 슈우웅 빠르게 가지 않고, 흔들흔들 요람처럼 움직였어요.',
      '아래에는 집 지붕들이 조용히 잠들어 있었어요. 창문 불빛도 하나둘 꺼지고, 골목길은 파란 이불을 덮은 것처럼 차분했어요.',
      '시현이는 작은 목소리로 물었어요. "구름아, 너도 잘 때가 있어?"',
      '구름 양탄자가 포근하게 대답했어요. "그럼. 나는 달님 옆에서 둥실둥실 쉬어. 오늘은 네 마음이 편해질 때까지 같이 있을게."',
      '조금 가자 별 요정들이 반짝반짝 작은 등불을 들고 나타났어요. 별 요정들은 소곤소곤 노래했어요. "자장자장, 오늘의 웃음도 코오 잠들어요."',
      '시현이는 오늘 만들었던 블록 탑을 떠올렸어요. 와르르 무너졌지만 다시 쌓아서 더 재미있었던 일이 생각났어요.',
      '구름 양탄자는 그 생각을 작은 별 주머니에 담아 주었어요. "즐거운 기억은 꿈속에서 반짝이는 길이 된단다."',
      '다음으로 낮에 조금 속상했던 마음도 떠올랐어요. 시현이는 입을 작게 오므리고 구름을 꼭 잡았어요.',
      '구름은 부드럽게 흔들렸어요. "속상한 마음도 쉬어야 해. 후우 하고 불면 작은 안개가 되어 멀리 흘러가."',
      '시현이가 후우 숨을 내쉬자 마음속 작은 안개가 몽글몽글 떠올랐어요. 달님이 그 안개를 은빛 숟가락으로 살살 저어 밤하늘에 풀어 주었어요.',
      '달님은 둥근 얼굴로 미소 지었어요. "시현아, 오늘도 충분히 잘했단다. 이제 눈꺼풀이 쉬어도 괜찮아."',
      '구름 양탄자는 다시 시현이 방 쪽으로 천천히 내려왔어요. 이불은 따뜻하게 펼쳐져 있었고 베개는 조용히 기다리고 있었어요.',
      '시현이는 구름에게 손을 흔들었어요. "내일도 와 줄래?" 구름은 폭신하게 끄덕이며 "네 꿈이 부르면 언제든 올게" 하고 말했어요.',
      '시현이가 이불 속에 쏙 들어가자 방 안이 포근하게 조용해졌어요. 창밖에서는 구름 양탄자가 아주 작은 목소리로 둥실둥실 자장가를 불렀답니다.'
    ]
  }
};
